// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylG1RYAPR981xvqcBoxNn_YIvuvyKENk',
    appId: '1:495475729075:web:05c2f1a7671073a64846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    authDomain: 'nomadmate.firebaseapp.com',
    storageBucket: 'nomadmate.appspot.com',
    measurementId: 'G-KQEX68T9DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9uIBYKJ-WQ7GJQN6nzyeAA9Pv1vUFHo',
    appId: '1:495475729075:android:ed1f79c8e1259b464846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQuTbg787nWRNzWjI5iHsi6KUNp1we6EI',
    appId: '1:495475729075:ios:0f846c6c7012138a4846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
    iosBundleId: 'com.example.nomad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQuTbg787nWRNzWjI5iHsi6KUNp1we6EI',
    appId: '1:495475729075:ios:d11750ffbf1dc89d4846c6',
    messagingSenderId: '495475729075',
    projectId: 'nomadmate',
    storageBucket: 'nomadmate.appspot.com',
    iosBundleId: 'com.example.nomad.RunnerTests',
  );
}
